- name: telemetry-framework-apb playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    apb_action: deprovision
  roles:
  - role: ansibleplaybookbundle.asb-modules
  - role: telemetry-framework-apb
